config/routes.rb
Kafe::Application.routes.draw do
  get '/order_links/new', controller: 'order_links', action: 'new', as: 'new_order_link'
  post '/order_links', controller: 'order_links', action: 'create', as: 'order_links'

  get '/order_links', controller: 'order_links', action: 'index'
  get '/order_links/:id', controller: 'order_links', action: 'show', as: 'order_link'

  get '/order_links/:id/edit', controller: 'order_links', action: 'edit', as: 'edit_order_link'
  patch '/order_links/:id', controller: 'order_links', action: 'update'

  delete '/order_links/:id', controller: 'order_links', action: 'destroy'

  get '/order_menus/new', controller: 'order_menus', action: 'new', as: 'new_order_menu'
  post '/order_menus', controller: 'order_menus', action: 'create', as: 'order_menus'

  get '/order_menus', controller: 'order_menus', action: 'index'
  get '/order_menus/:id', controller: 'order_menus', action: 'show', as: 'order_menu'

  get '/order_menus/:id/edit', controller: 'order_menus', action: 'edit', as: 'edit_order_menu'
  patch '/order_menus/:id', controller: 'order_menus', action: 'update'

  delete '/order_menus/:id', controller: 'order_menus', action: 'destroy'

  get '/orders/new', controller: 'orders', action: 'new', as: 'new_order'
  post '/orders', controller: 'orders', action: 'create', as: 'orders'

  get '/orders', controller: 'orders', action: 'index'
  get '/orders/:id', controller: 'orders', action: 'show', as: 'order'

  get '/orders/:id/edit', controller: 'orders', action: 'edit', as: 'edit_order'
  patch '/orders/:id', controller: 'orders', action: 'update'

  delete '/orders/:id', controller: 'orders', action: 'destroy'

  get '/todays_specials/new', controller: 'todays_specials', action: 'new', as: 'new_todays_special'
  post '/todays_specials', controller: 'todays_specials', action: 'create', as: 'todays_specials'

  get '/todays_specials', controller: 'todays_specials', action: 'index'
  get '/todays_specials/:id', controller: 'todays_specials', action: 'show', as: 'todays_special'

  get '/todays_specials/:id/edit', controller: 'todays_specials', action: 'edit', as: 'edit_todays_special'
  patch '/todays_specials/:id', controller: 'todays_specials', action: 'update'

  delete '/todays_specials/:id', controller: 'todays_specials', action: 'destroy'

  get '/day_menus/new', controller: 'day_menus', action: 'new', as: 'new_day_menu'
  post '/day_menus', controller: 'day_menus', action: 'create', as: 'day_menus'

  get '/day_menus', controller: 'day_menus', action: 'index'
  get '/day_menus/:id', controller: 'day_menus', action: 'show', as: 'day_menu'

  get '/day_menus/:id/edit', controller: 'day_menus', action: 'edit', as: 'edit_day_menu'
  patch '/day_menus/:id', controller: 'day_menus', action: 'update'

  delete '/day_menus/:id', controller: 'day_menus', action: 'destroy'

  get '/item_menus/new', controller: 'item_menus', action: 'new', as: 'new_item_menu'
  post '/item_menus', controller: 'item_menus', action: 'create', as: 'item_menus'

  get '/item_menus', controller: 'item_menus', action: 'index'
  get '/item_menus/:id', controller: 'item_menus', action: 'show', as: 'item_menu'

  get '/item_menus/:id/edit', controller: 'item_menus', action: 'edit', as: 'edit_item_menu'
  patch '/item_menus/:id', controller: 'item_menus', action: 'update'

  delete '/item_menus/:id', controller: 'item_menus', action: 'destroy'

  devise_for :users
  root "users#index"

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/todays_special.rb
class TodaysSpecial < ActiveRecord::Base
	has_many :order_links
	belongs_to :item_menu
	belongs_to :day_menu 
end

app/controllers/todays_specials_controller.rb
class TodaysSpecialsController < ApplicationController
before_action(:authorize_user)

def authorize_user
unless user_signed_in?
  redirect_to new_user_session_path, notice: "You must be signed in."
end 
end
  def index
    @todays_specials = TodaysSpecial
    @todays_specials = TodaysSpecial.order(params[:sort]) if params[:sort]
    @todays_specials = @todays_specials.all
  end

  def show
    @todays_special = TodaysSpecial.find_by(id: params[:id])
  end

  def new
  end

  def create
    @todays_special = TodaysSpecial.new
    @todays_special.day_menu_id = params[:day_menu_id]
    @todays_special.item_menu_id = params[:item_menu_id]
    @todays_special.cuisine = params[:cuisine]

    if @todays_special.save
      redirect_to todays_specials_url, notice: "Todays special created successfully."
    else
      render 'new'
    end
  end

  def edit
    @todays_special = TodaysSpecial.find_by(id: params[:id])
  end

  def update
    @todays_special = TodaysSpecial.find_by(id: params[:id])
    @todays_special.day_menu_id = params[:day_menu_id]
    @todays_special.item_menu_id = params[:item_menu_id]
    @todays_special.cuisine = params[:cuisine]

    if @todays_special.save
      redirect_to todays_specials_url, notice: "Todays special updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @todays_special = TodaysSpecial.find_by(id: params[:id])
    @todays_special.destroy

    redirect_to todays_specials_url, notice: "Todays special deleted."
  end
end

app/views/todays_specials/edit.html.erb
<div class="page-header">
  <h1>Editing Todays Special #<%= @todays_special.id %></h1>
</div>

<%= form_tag(todays_special_url(@todays_special), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :day_menu_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :day_menu_id, @todays_special.day_menu_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_menu_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :item_menu_id, @todays_special.item_menu_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :cuisine, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :cuisine, @todays_special.cuisine, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Todays Special", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/todays_specials/index.html.erb
<div class="page-header">
  <h1>Todays specials</h1>
</div>

<p><%= link_to 'Add a New Todays Special', new_todays_special_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= link_to 'Day Menu', todays_specials_url(sort: "day_menu_id") %></th>
      <th>Item menu</th>
      <th>Cuisine</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todays_specials.each do |todays_special| %>
      <tr>
      
        <td><%= todays_special.day_menu.weekday %></td>
        <td><%= todays_special.item_menu.item_name %></td>
        <td><%= todays_special.cuisine %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, todays_special_url(todays_special), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_todays_special_url(todays_special), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, todays_special_url(todays_special), method: 'delete', data: { confirm: "Do you really want to delete this todays_special?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todays_specials/new.html.erb
<div class="page-header">
  <h1>New Todays Special</h1>
</div>

<%= form_tag(todays_specials_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :day_menu_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :day_menu_id, options_from_collection_for_select(DayMenu.all, :id, :weekday ) %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_menu_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :item_menu_id, options_from_collection_for_select(ItemMenu.all, :id, :item_name ) %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :cuisine, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :cuisine, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Todays Special", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/todays_specials/show.html.erb
<div class="page-header">
  <h1>Todays Special #<%= @todays_special.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Day menu</dt>
  <dd><%= @todays_special.day_menu_id %></dd>

  <dt>Item menu</dt>
  <dd><%= @todays_special.item_menu_id %></dd>

  <dt>Cuisine</dt>
  <dd><%= @todays_special.cuisine %></dd>

</dl>