config/routes.rb
Kafe::Application.routes.draw do
  get '/order_links/new', controller: 'order_links', action: 'new', as: 'new_order_link'
  post '/order_links', controller: 'order_links', action: 'create', as: 'order_links'

  get '/order_links', controller: 'order_links', action: 'index'
  get '/order_links/:id', controller: 'order_links', action: 'show', as: 'order_link'

  get '/order_links/:id/edit', controller: 'order_links', action: 'edit', as: 'edit_order_link'
  patch '/order_links/:id', controller: 'order_links', action: 'update'

  delete '/order_links/:id', controller: 'order_links', action: 'destroy'

  get '/order_menus/new', controller: 'order_menus', action: 'new', as: 'new_order_menu'
  post '/order_menus', controller: 'order_menus', action: 'create', as: 'order_menus'

  get '/order_menus', controller: 'order_menus', action: 'index'
  get '/order_menus/:id', controller: 'order_menus', action: 'show', as: 'order_menu'

  get '/order_menus/:id/edit', controller: 'order_menus', action: 'edit', as: 'edit_order_menu'
  patch '/order_menus/:id', controller: 'order_menus', action: 'update'

  delete '/order_menus/:id', controller: 'order_menus', action: 'destroy'

  get '/orders/new', controller: 'orders', action: 'new', as: 'new_order'
  post '/orders', controller: 'orders', action: 'create', as: 'orders'

  get '/orders', controller: 'orders', action: 'index'
  get '/orders/:id', controller: 'orders', action: 'show', as: 'order'

  get '/orders/:id/edit', controller: 'orders', action: 'edit', as: 'edit_order'
  patch '/orders/:id', controller: 'orders', action: 'update'

  delete '/orders/:id', controller: 'orders', action: 'destroy'

  get '/todays_specials/new', controller: 'todays_specials', action: 'new', as: 'new_todays_special'
  post '/todays_specials', controller: 'todays_specials', action: 'create', as: 'todays_specials'

  get '/todays_specials', controller: 'todays_specials', action: 'index'
  get '/todays_specials/:id', controller: 'todays_specials', action: 'show', as: 'todays_special'

  get '/todays_specials/:id/edit', controller: 'todays_specials', action: 'edit', as: 'edit_todays_special'
  patch '/todays_specials/:id', controller: 'todays_specials', action: 'update'

  delete '/todays_specials/:id', controller: 'todays_specials', action: 'destroy'

  get '/day_menus/new', controller: 'day_menus', action: 'new', as: 'new_day_menu'
  post '/day_menus', controller: 'day_menus', action: 'create', as: 'day_menus'

  get '/day_menus', controller: 'day_menus', action: 'index'
  get '/day_menus/:id', controller: 'day_menus', action: 'show', as: 'day_menu'

  get '/day_menus/:id/edit', controller: 'day_menus', action: 'edit', as: 'edit_day_menu'
  patch '/day_menus/:id', controller: 'day_menus', action: 'update'

  delete '/day_menus/:id', controller: 'day_menus', action: 'destroy'

  get '/item_menus/new', controller: 'item_menus', action: 'new', as: 'new_item_menu'
  post '/item_menus', controller: 'item_menus', action: 'create', as: 'item_menus'

  get '/item_menus', controller: 'item_menus', action: 'index'
  get '/item_menus/:id', controller: 'item_menus', action: 'show', as: 'item_menu'

  get '/item_menus/:id/edit', controller: 'item_menus', action: 'edit', as: 'edit_item_menu'
  patch '/item_menus/:id', controller: 'item_menus', action: 'update'

  delete '/item_menus/:id', controller: 'item_menus', action: 'destroy'

  devise_for :users
  root "users#index"

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/item_menu.rb
class ItemMenu < ActiveRecord::Base
	has_many :todays_specials
	has_many :day_menus, :through => :todays_specials
	mount_uploader :item_picture, ImageUploader
end

app/controllers/item_menus_controller.rb
class ItemMenusController < ApplicationController
before_action(:authorize_user)

def authorize_user
unless user_signed_in?
  redirect_to new_user_session_path, notice: "You must be signed in."
end 
end

  def index
    @item_menus = ItemMenu.all
    @item_menus = ItemMenu.order(params[:sort]) if params[:sort]
    @item_menus = @item_menus.all
  end

  def show
    @item_menu = ItemMenu.find_by(id: params[:id])
  end

  def new
  end

  def create
    @item_menu = ItemMenu.new
    @item_menu.item_name = params[:item_name]
    @item_menu.item_category = params[:item_category]
    @item_menu.item_picture = params[:item_picture]
    @item_menu.item_price = params[:item_price]
    @item_menu.item_description = params[:item_description]

    if @item_menu.save
      redirect_to item_menus_url, notice: "Item menu created successfully."
    else
      render 'new'
    end
  end

  def edit
    @item_menu = ItemMenu.find_by(id: params[:id])
  end

  def update
    @item_menu = ItemMenu.find_by(id: params[:id])
    @item_menu.item_name = params[:item_name]
    @item_menu.item_category = params[:item_category]
    @item_menu.item_picture = params[:item_picture]
    @item_menu.item_price = params[:item_price]
    @item_menu.item_description = params[:item_description]

    if @item_menu.save
      redirect_to item_menus_url, notice: "Item menu updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @item_menu = ItemMenu.find_by(id: params[:id])
    @item_menu.destroy

    redirect_to item_menus_url, notice: "Item menu deleted."
  end
end

app/views/item_menus/edit.html.erb
<div class="page-header">
  <h1>Editing Item Menu #<%= @item_menu.id %></h1>
</div>

<%= form_tag(item_menu_url(@item_menu), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :item_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_name, @item_menu.item_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_category, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_category, @item_menu.item_category, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_picture, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_picture, @item_menu.item_picture, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_price, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_price, @item_menu.item_price, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_description, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_description, @item_menu.item_description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Item Menu", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/item_menus/index.html.erb
<div class="page-header">
  <h1>Item menus</h1>
</div>

<p><%= link_to 'Add a new item to menu', new_item_menu_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= link_to 'Item name', item_menus_url(sort: "item_name") %></th>
      <th><%= link_to 'Item category', item_menus_url(sort: "item_category") %></th>
      <th>Item picture</th>
      <th>Item price</th>
      <th>Item description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @item_menus.each do |item_menu| %>
      <tr>
        <td><%= item_menu.item_name %></td>
        <td><%= item_menu.item_category %></td>
        <td><%= image_tag item_menu.item_picture, :width => 100 %></td>
        <td><%= item_menu.item_price %></td>
        <td><%= item_menu.item_description %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, item_menu_url(item_menu), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_item_menu_url(item_menu), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, item_menu_url(item_menu), method: 'delete', data: { confirm: "Do you really want to delete this item_menu?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/item_menus/new.html.erb
<div class="page-header">
  <h1>New Item Menu</h1>
</div>

<%= form_tag(item_menus_url, method: 'post', class: 'form-horizontal', multipart: true) do %>
  <div class="form-group">
    <%= label_tag :item_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_category, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_category, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_picture, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= file_field_tag :item_picture, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_price, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_price, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_description, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_description, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Item Menu", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/item_menus/show.html.erb
<div class="page-header">
  <h1>Item Menu #<%= @item_menu.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Item name</dt>
  <dd><%= @item_menu.item_name %></dd>

  <dt>Item category</dt>
  <dd><%= @item_menu.item_category %></dd>

  <dt>Item picture</dt>
  <dd><%= @item_menu.item_picture %></dd>

  <dt>Item price</dt>
  <dd><%= @item_menu.item_price %></dd>

  <dt>Item description</dt>
  <dd><%= @item_menu.item_description %></dd>

</dl>