config/routes.rb
Kafe::Application.routes.draw do
  get '/order_links/new', controller: 'order_links', action: 'new', as: 'new_order_link'
  post '/order_links', controller: 'order_links', action: 'create', as: 'order_links'

  get '/order_links', controller: 'order_links', action: 'index'
  get '/order_links/:id', controller: 'order_links', action: 'show', as: 'order_link'

  get '/order_links/:id/edit', controller: 'order_links', action: 'edit', as: 'edit_order_link'
  patch '/order_links/:id', controller: 'order_links', action: 'update'

  delete '/order_links/:id', controller: 'order_links', action: 'destroy'

  get '/order_menus/new', controller: 'order_menus', action: 'new', as: 'new_order_menu'
  post '/order_menus', controller: 'order_menus', action: 'create', as: 'order_menus'

  get '/order_menus', controller: 'order_menus', action: 'index'
  get '/order_menus/:id', controller: 'order_menus', action: 'show', as: 'order_menu'

  get '/order_menus/:id/edit', controller: 'order_menus', action: 'edit', as: 'edit_order_menu'
  patch '/order_menus/:id', controller: 'order_menus', action: 'update'

  delete '/order_menus/:id', controller: 'order_menus', action: 'destroy'

  get '/orders/new', controller: 'orders', action: 'new', as: 'new_order'
  post '/orders', controller: 'orders', action: 'create', as: 'orders'

  get '/orders', controller: 'orders', action: 'index'
  get '/orders/:id', controller: 'orders', action: 'show', as: 'order'

  get '/orders/:id/edit', controller: 'orders', action: 'edit', as: 'edit_order'
  patch '/orders/:id', controller: 'orders', action: 'update'

  delete '/orders/:id', controller: 'orders', action: 'destroy'

  get '/todays_specials/new', controller: 'todays_specials', action: 'new', as: 'new_todays_special'
  post '/todays_specials', controller: 'todays_specials', action: 'create', as: 'todays_specials'

  get '/todays_specials', controller: 'todays_specials', action: 'index'
  get '/todays_specials/:id', controller: 'todays_specials', action: 'show', as: 'todays_special'

  get '/todays_specials/:id/edit', controller: 'todays_specials', action: 'edit', as: 'edit_todays_special'
  patch '/todays_specials/:id', controller: 'todays_specials', action: 'update'

  delete '/todays_specials/:id', controller: 'todays_specials', action: 'destroy'

  get '/day_menus/new', controller: 'day_menus', action: 'new', as: 'new_day_menu'
  post '/day_menus', controller: 'day_menus', action: 'create', as: 'day_menus'

  get '/day_menus', controller: 'day_menus', action: 'index'
  get '/day_menus/:id', controller: 'day_menus', action: 'show', as: 'day_menu'

  get '/day_menus/:id/edit', controller: 'day_menus', action: 'edit', as: 'edit_day_menu'
  patch '/day_menus/:id', controller: 'day_menus', action: 'update'

  delete '/day_menus/:id', controller: 'day_menus', action: 'destroy'

  get '/item_menus/new', controller: 'item_menus', action: 'new', as: 'new_item_menu'
  post '/item_menus', controller: 'item_menus', action: 'create', as: 'item_menus'

  get '/item_menus', controller: 'item_menus', action: 'index'
  get '/item_menus/:id', controller: 'item_menus', action: 'show', as: 'item_menu'

  get '/item_menus/:id/edit', controller: 'item_menus', action: 'edit', as: 'edit_item_menu'
  patch '/item_menus/:id', controller: 'item_menus', action: 'update'

  delete '/item_menus/:id', controller: 'item_menus', action: 'destroy'

  devise_for :users
  root "users#index"

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Kafe</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
      background-image: -webkit-linear-gradient(top left, #FFFFFF 25%, #E0E6F8 80%);
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_url(current_user.id) %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Users", users_url %></li>
          <li><%= link_to "Item Menus", item_menus_url %></li>
          <li><%= link_to "Day Menus", day_menus_url %></li>
          <li><%= link_to "Orders", orders_url %></li>
          <li><%= link_to "Order Menus", order_menus_url %></li>
          <li><%= link_to "Todays Specials", todays_specials_url %></li>
          <li><%= link_to "Order Links", order_links_url %></li>
          <li><a href="#">About</a></li>

        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>




        
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>


  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>